### ISSUE TITLE
Container does not include the docker executable required for the "docker builder"

### ISSUE THREAD

**Issue by pickgr** [unifio/dockerfile-packer#9]
docker output will be in this color.

Build 'docker' errored: exec: "docker": executable file not found in $PATH

==> Some builds didn't complete successfully and had errors:
--> docker: exec: "docker": executable file not found in $PATH

==> Builds finished but no artifacts were created.

**Comment by pickgr** [comment]
I was able to get docker installed, but ran into some challenges getting the docker daemon running as it looks like it's dependent on openrc which is not really supported in alpine linux for somewhat philosophical reasons.

I did find this post:

http://janhapke.com/blog/installing-docker-daemon-on-alpine-linux/

**Comment by blakeneyops** [comment]
Hi Garret,

What I have found to work best is to connect the Docker client to the host Docker daemon. The only requirement is that the Docker client version cannot be newer than that of the server daemon. I intentionally lowered the version in the image to 1.9.1 to meet the requirements for the CircleCI environment. Will 1.9.1 meet your needs?

Have a look at 3ef17f1e1b765e316a4b101876bf0acc2087217a

The build results are here: https://circleci.com/gh/unifio/dockerfile-packer/87

**Comment by pickgr** [comment]
Our bamboo instances currently have

Docker version 1.9.1, build a34a1d5/1.9.1

so hopefully this will work.  I'll give it a try today.

**Comment by yuhunglin** [comment]
@pickgr has the issue been dealt with?

**Comment by pickgr** [comment]
Yeah - I believe we can close this.  Trying to remember what happened here...

I think we went down the path of trying to run docker within docker and got fairly close.  As you can imagine it got kinda hairy...

Ultimately, we made the decision to not use packer to create our docker images anymore.  The Dockerfile seems more standard and something that developer's are likely to be more familiar with.

Cc: @blakeneyops @cristobal23
